# Generated by Django 5.0.3 on 2024-03-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userurlmodel",
            name="categories",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="rest_api.categoriesmodel",
            ),
        ),
        migrations.AlterField(
            model_name="userurlmodel",
            name="tags",
            field=models.ManyToManyField(blank=True, to="rest_api.tagsmodel"),
        ),
    ]
