# Generated by Django 5.0.3 on 2024-03-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0002_alter_userurlmodel_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoriesmodel",
            old_name="category",
            new_name="categories",
        ),
    ]
