# Generated by Django 5.0.3 on 2024-03-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0003_rename_category_categoriesmodel_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoriesmodel",
            old_name="categories",
            new_name="category",
        ),
    ]
