# Generated by Django 5.0.3 on 2024-03-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0004_rename_categories_categoriesmodel_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userurlmodel",
            old_name="categories",
            new_name="category",
        ),
    ]
