# Generated by Django 5.0.3 on 2024-03-22 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0005_rename_categories_userurlmodel_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userurlmodel",
            name="tags",
            field=models.ManyToManyField(to="rest_api.tagsmodel"),
        ),
        migrations.AlterUniqueTogether(
            name="userurlmodel",
            unique_together={("user", "url")},
        ),
    ]
