# Generated by Django 5.0.3 on 2024-03-23 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0006_alter_userurlmodel_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="urlmodel",
            name="title",
            field=models.CharField(default="UnTitle", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="categoriesmodel",
            unique_together={("user", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="tagsmodel",
            unique_together={("user", "tag")},
        ),
        migrations.AlterUniqueTogether(
            name="urlmodel",
            unique_together={("user", "url")},
        ),
    ]
